id = "qlik"
name = "Qlik"
description = "Syntax highlighting for Qlik Sense / QlikView script files (.qvs)"
version = "0.1.0"
schema_version = 1
authors = ["Stanislav Chernov <bintocher@yandex.com>"]
repository = "https://github.com/bintocher/zed-qlik-editor"

[grammars.qlik]
repository = "https://github.com/bintocher/zed-qlik-tree-sitter"
commit = "6390263559b69e32ab3acc7c6453772f66191ea3"
