id = "qlik"
name = "Qlik"
description = "Syntax highlighting for Qlik Sense / QlikView script files (.qvs)"
version = "0.1.0"
schema_version = 1
authors = ["bintocher <https://github.com/bintocher>"]
repository = "https://github.com/bintocher/zed-qlik-editor"

[grammars.qlik]
repository = "https://github.com/bintocher/zed-qlik-tree-sitter"
rev = "099b0945037bce8d4a762928c6cc14b747fb9768"
